
version: '2'
services:
  db:
    image: postgres:alpine
    restart: always
    networks:
      - db
    volumes:
      - "//%cd%/var/lib/postgresql/data"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  api:
    image: conor01/passengerpart2
    ports:
      - 8802:8801
    volumes:
      - /data/application
    networks:
      - db
    depends_on:
      - db
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/postgres
networks:
  db:

